name: alma_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.2
  flutter_svg: ^1.0.3
  flutter_screenutil: ^5.3.1
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.10
  cloud_firestore: ^3.1.10 
  firebase_storage: ^10.2.11 
  google_sign_in: ^5.3.0
  image_picker: ^0.8.5
  provider: ^6.0.1
  video_player: ^2.2.18
  uuid: ^3.0.6
  flutter_facebook_auth: ^4.3.0
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  google_mobile_ads: ^1.2.0
  flutter_admin_scaffold: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.ttf
        
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
